from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

TEAMPREVIEW_SUMMARY = [
    "Omitted here because the teampreview choice set is global and unchanged across battles.",
    "Total teampreview legal choices: 90",
    "Reference examples: team 1234, team 4615, team 5634",
]

RENDERER_NOTES = [
    "Renderer note: an earlier ad hoc version of this document skipped some decision windows.",
    "For rust-sync-0 specifically, the source trace contains a recorded p1 move request at turn 2 between the turn 1 and turn 3 windows.",
    "That gap was a documentation/rendering mistake in the markdown generator, not a missing Rust-engine request in the recorded trace.",
    "Legal Choices in this document are generated by the Python sync driver from the synchronized poke-env-style battle state and sanitized request, not emitted directly by the Rust engine.",
]


def _render_log_entries(entries: list[Any]) -> list[str]:
    if not entries:
        return ["<no new logs>"]

    raw_lines: list[str] = []
    normalized_lines: list[str] = []

    for entry in entries:
        if isinstance(entry, dict):
            raw_value = entry.get("raw")
            normalized_value = entry.get("normalized")
            raw_text = "" if raw_value is None else str(raw_value)
            normalized_text = raw_text if normalized_value is None else str(normalized_value)
            if raw_text:
                raw_lines.append(raw_text)
            if normalized_text:
                normalized_lines.append(normalized_text)
            continue

        text = str(entry)
        raw_lines.append(text)
        normalized_lines.append(text)

    if raw_lines == normalized_lines:
        return raw_lines

    rendered = ["raw:"]
    rendered.extend(f"  {line}" for line in raw_lines)
    rendered.append("normalized:")
    rendered.extend(f"  {line}" for line in normalized_lines)
    return rendered


def _render_legal_choices(request_type: str | None, legal_choices: list[str]) -> list[str]:
    if request_type == "teamPreview":
        return list(TEAMPREVIEW_SUMMARY)
    return legal_choices


def _render_choice_line(
    side: str,
    window: dict[str, Any],
    result: dict[str, Any] | None,
    *,
    forced_rejected: bool = False,
) -> str:
    choice = window.get("submitted_choices", {}).get(side)
    if result is None:
        if forced_rejected:
            return f"Choice: {choice} | rejected=True | fallback_recovered=False"
        return f"Choice: {choice}"

    rejected = forced_rejected or (not bool(result.get("initial_acceptance", {}).get(side, False)))
    fallback_recovered = bool(result.get("fallback_recovered", {}).get(side, False))
    return (
        f"Choice: {choice} | rejected={str(rejected)} | "
        f"fallback_recovered={str(fallback_recovered)}"
    )


def _event_has_rejection(result: dict[str, Any] | None) -> bool:
    if result is None:
        return False
    initial_acceptance = result.get("initial_acceptance", {})
    return (not bool(initial_acceptance.get("p1", True))) or (
        not bool(initial_acceptance.get("p2", True))
    )


def _first_rejection_turn(record: dict[str, Any]) -> int | None:
    trace = record.get("trace", [])
    for index, event in enumerate(trace):
        if event.get("event_type") != "decision_window":
            continue
        paired_result = None
        if index + 1 < len(trace) and trace[index + 1].get("event_type") == "decision_result":
            paired_result = trace[index + 1]
        if _event_has_rejection(paired_result):
            turn_before = event.get("turn_before")
            return int(turn_before) if turn_before is not None else None
    return None


def _load_first_rejection_turns(rejection_jsonl_path: Path | None) -> dict[str, int]:
    if rejection_jsonl_path is None or not rejection_jsonl_path.exists():
        return {}

    first_rejection_turns: dict[str, int] = {}
    for line in rejection_jsonl_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        if event.get("event_type") != "rejected_choice":
            continue
        battle_tag = event.get("battle_tag")
        turn_before = event.get("turn_before")
        if battle_tag is None or turn_before is None:
            continue
        turn_value = int(turn_before)
        existing = first_rejection_turns.get(battle_tag)
        if existing is None or turn_value < existing:
            first_rejection_turns[battle_tag] = turn_value
    return first_rejection_turns


def _render_record(
    record: dict[str, Any],
    battle_index: int,
    side: str,
    *,
    stop_after_first_rejection: bool,
    first_rejection_turn: int | None,
) -> list[str]:
    lines = [
        f"## Battle {battle_index}: {record['battle_tag']}",
        "",
        f"Winner: {record.get('winner')}",
        f"Truncated: {record.get('truncated')}",
        f"Final turn: {record.get('final_turn')}",
        "",
    ]

    trace = record.get("trace", [])
    protocol_log = record.get("protocol_log", {}).get(side, [])
    previous_log_index = 0
    step_index = 1

    for index, event in enumerate(trace):
        if event.get("event_type") != "decision_window":
            continue

        side_state = event.get(side)
        if not side_state:
            continue

        paired_result = None
        if index + 1 < len(trace) and trace[index + 1].get("event_type") == "decision_result":
            paired_result = trace[index + 1]

        before_len = int(side_state.get("protocol_log_length_before", previous_log_index))
        log_entries = protocol_log[previous_log_index:before_len]
        previous_log_index = before_len

        request_type = side_state.get("request_type")
        forced_rejected = first_rejection_turn is not None and int(event.get("turn_before", -1)) >= first_rejection_turn
        lines.extend(
            [
                f"### Step {step_index} (turn {event.get('turn_before')}, {request_type})",
                "",
                "Logs Until Request:",
                "```text",
                *_render_log_entries(log_entries),
                "```",
                "",
                "Battle State:",
                "```text",
                side_state.get("battle_state_poke_env", ""),
                "```",
                "",
                "Request:",
                "```text",
                side_state.get("battle_state_request", ""),
                "```",
                "",
                "Legal Choices:",
                "```text",
                *_render_legal_choices(request_type, side_state.get("legal_choices", [])),
                "```",
                "",
                _render_choice_line(side, event, paired_result, forced_rejected=forced_rejected),
                "",
            ]
        )
        step_index += 1

        if stop_after_first_rejection and (
            _event_has_rejection(paired_result)
            or (first_rejection_turn is not None and int(event.get("turn_before", -1)) >= first_rejection_turn)
        ):
            break

    return lines


def render_document(
    *,
    records_dir: Path,
    summary_path: Path,
    output_path: Path,
    limit: int,
    side: str,
    max_first_rejection_turn: int | None,
    stop_after_first_rejection: bool,
    rejection_jsonl_path: Path | None,
) -> str:
    first_rejection_turns = _load_first_rejection_turns(rejection_jsonl_path)
    selected_records: list[tuple[Path, dict[str, Any], int | None]] = []
    for record_path in sorted(records_dir.glob("*.json")):
        record = json.loads(record_path.read_text(encoding="utf-8"))
        first_rejection_turn = first_rejection_turns.get(record.get("battle_tag"))
        if first_rejection_turn is None:
            first_rejection_turn = _first_rejection_turn(record)
        if max_first_rejection_turn is not None:
            if first_rejection_turn is None or first_rejection_turn > max_first_rejection_turn:
                continue
        selected_records.append((record_path, record, first_rejection_turn))
        if len(selected_records) >= limit:
            break

    title = "# Early Rejection Error Battles" if max_first_rejection_turn is not None else "# Ten Error Battles"
    lines = [
        title,
        "",
        f"Source records: {records_dir.as_posix()}",
        f"Source summary: {summary_path.as_posix()}",
        (
            "Rejection source: trace decision_result metadata"
            if rejection_jsonl_path is None
            else f"Rejection source: {rejection_jsonl_path.as_posix()}"
        ),
        (
            "Filter: none"
            if max_first_rejection_turn is None
            else f"Filter: first rejection turn <= {max_first_rejection_turn}"
        ),
        f"Stop after first rejection: {stop_after_first_rejection}",
        "",
        "## Rendering Notes",
        "",
        *[f"- {note}" for note in RENDERER_NOTES],
        "",
        f"Distinct battle tags included: {len(selected_records)}",
        "",
    ]

    for battle_index, (_, record, first_rejection_turn) in enumerate(selected_records, start=1):
        lines.extend(
            _render_record(
                record,
                battle_index,
                side,
                stop_after_first_rejection=stop_after_first_rejection,
                first_rejection_turn=first_rejection_turn,
            )
        )

    rendered = "\n".join(lines).rstrip() + "\n"
    output_path.write_text(rendered, encoding="utf-8")
    return rendered


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--records-dir", required=True)
    parser.add_argument("--summary-path", required=True)
    parser.add_argument("--output-path", required=True)
    parser.add_argument("--limit", type=int, default=10)
    parser.add_argument("--side", default="p1", choices=["p1", "p2"])
    parser.add_argument("--max-first-rejection-turn", type=int)
    parser.add_argument("--stop-after-first-rejection", action="store_true")
    parser.add_argument("--rejection-jsonl-path")
    args = parser.parse_args()

    render_document(
        records_dir=Path(args.records_dir),
        summary_path=Path(args.summary_path),
        output_path=Path(args.output_path),
        limit=args.limit,
        side=args.side,
        max_first_rejection_turn=args.max_first_rejection_turn,
        stop_after_first_rejection=args.stop_after_first_rejection,
        rejection_jsonl_path=(
            Path(args.rejection_jsonl_path) if args.rejection_jsonl_path is not None else None
        ),
    )


if __name__ == "__main__":
    main()
