"""Concatenates BCPlayer + dependencies into examples/one_file_bc_player.py.

Mechanical concatenation: reads each source file, drops the
`from elitefurretai.*` / `import elitefurretai.*` lines, and writes the
remainder in dependency order. Third-party imports (torch, poke_env, numpy)
are left in-place per file — Python is fine with re-imports.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path("/home/cayman/Repositories/EliteFurretAI")
SRC = ROOT / "src" / "elitefurretai"
OUT = ROOT / "examples" / "one_file_bc_player.py"

INTERNAL_IMPORT_RE = re.compile(
    r"^(?:from\s+elitefurretai[.\w]*\s+import\s+.*|import\s+elitefurretai[.\w]*.*)$"
)


def strip_internal_imports(text: str) -> str:
    """Drop any `from elitefurretai...` or `import elitefurretai...` line.

    Also drops the lazy import inside BCPlayer._load_model (which sits indented
    inside a method) so we can rely on the inlined `build_model_from_config`.
    """
    out_lines = []
    for line in text.splitlines():
        # Match both module-level and indented imports
        stripped = line.lstrip()
        if INTERNAL_IMPORT_RE.match(stripped):
            continue
        out_lines.append(line)
    return "\n".join(out_lines) + "\n"


def read(path: Path) -> str:
    return path.read_text()


def slice_top_module_docstring(text: str) -> str:
    """Remove the leading module docstring + coding declaration so we don't get
    multiple docstrings concatenated into the output file. Keeps everything
    after the first blank line that follows the docstring.
    """
    lines = text.splitlines(keepends=True)
    i = 0
    # Skip coding/shebang lines
    while i < len(lines) and (
        lines[i].startswith("#") or lines[i].strip() == ""
    ):
        i += 1
    # If a triple-quoted docstring starts here, skip to its end
    if i < len(lines):
        stripped = lines[i].lstrip()
        for quote in ('"""', "'''"):
            if stripped.startswith(quote):
                # Single-line docstring on the same line
                rest = stripped[3:]
                if quote in rest:
                    i += 1
                    break
                # Multi-line — find closing
                i += 1
                while i < len(lines) and quote not in lines[i]:
                    i += 1
                if i < len(lines):
                    i += 1
                break
    return "".join(lines[i:])


def section_header(title: str) -> str:
    bar = "# " + "=" * 76
    return f"\n\n{bar}\n# {title}\n{bar}\n\n"


def stub_battle_to_str() -> str:
    return (
        "def battle_to_str(battle, opp=None) -> str:\n"
        "    \"\"\"Stub: only used in error-paths inside BattleInference.\"\"\"\n"
        "    return f\"<Battle {getattr(battle, 'battle_tag', '?')}>\"\n"
    )


def extract_learners_snippet() -> str:
    """Pull just the symbols we need from learners.py."""
    text = (SRC / "rl" / "learners.py").read_text()
    # We need: _normalize_config_value, _config_to_flat_arch, build_model_from_config
    # Match each by header line and capture until the next top-level def/class.
    out_parts: list[str] = []
    wanted = ["_normalize_config_value", "_config_to_flat_arch", "build_model_from_config"]
    lines = text.splitlines(keepends=True)
    for name in wanted:
        # Find `def name(` at column 0
        start = None
        for idx, line in enumerate(lines):
            if line.startswith(f"def {name}("):
                start = idx
                break
        assert start is not None, f"could not find def {name}"
        end = start + 1
        while end < len(lines):
            line = lines[end]
            # Top-level boundary: next `def `, `class `, or `name =` at col 0.
            if line.startswith(("def ", "class ")) or re.match(r"^[A-Z_][A-Z0-9_]*\s*=", line):
                break
            end += 1
        out_parts.append("".join(lines[start:end]))
    return "\n\n".join(out_parts)


def build() -> None:
    header = '''"""Standalone single-file BCPlayer + dependencies.

Generated by scripts/build_one_file_bc_player.py — do not hand-edit.

Drop this file next to a model checkpoint (e.g. rose-sun-108_best.pt) and
import :class:`BCPlayer`. Requires the EliteFurretAI poke-env fork, PyTorch,
and NumPy to be installed in the runtime environment.

Quick start::

    from one_file_bc_player import BCPlayer
    player = BCPlayer(
        model_filepath="rose-sun-108_best.pt",
        battle_format="gen9vgc2023regc",
        device="cpu",
    )

This file inlines (in dependency order):
  * encoder.py        — MDBO action encoding
  * masking.py        — fast_get_action_mask
  * inference_utils   — battle_to_str (stubbed; only used in error paths)
  * battle_inference  — BattleInference (used by Embedder)
  * embedder.py       — Embedder + TRACKED_* tables + build_*_to_id
  * model_archs.py    — TransformerThreeHeadedModel + sub-encoders
  * learners.py       — build_model_from_config + helpers
  * bc_player.py      — BCPlayer itself
"""
'''

    pieces: list[str] = [header]

    pieces.append(section_header("encoder.py — MDBO action encoding"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "etl" / "encoder.py"))))

    pieces.append(section_header("masking.py — fast_get_action_mask"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "rl" / "masking.py"))))

    pieces.append(section_header("inference_utils — battle_to_str stub"))
    pieces.append(stub_battle_to_str())

    pieces.append(section_header("battle_inference.py — BattleInference"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "inference" / "battle_inference.py"))))

    pieces.append(section_header("embedder.py — Embedder"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "etl" / "embedder.py"))))

    pieces.append(section_header("model_archs.py — TransformerThreeHeadedModel"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "supervised" / "model_archs.py"))))

    pieces.append(section_header("learners.py — build_model_from_config (extracted)"))
    pieces.append(extract_learners_snippet())

    pieces.append(section_header("bc_player.py — BCPlayer"))
    pieces.append(strip_internal_imports(slice_top_module_docstring(read(SRC / "agents" / "bc_player.py"))))

    OUT.write_text("".join(pieces))
    print(f"Wrote {OUT} — {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    build()
