import queue
from types import SimpleNamespace
from typing import cast
from unittest.mock import MagicMock

from poke_env import ServerConfiguration

from elitefurretai.etl import Embedder, TeamRepo
from elitefurretai.rl.opponents import (
    OpponentPool,
    WorkerOpponentFactory,
    largest_remainder_apportionment,
)
from elitefurretai.rl.rl_trajectory_player import RLTrajectoryPlayer


class _DummyTeamRepo:
    def sample_team(self, battle_format, subdirectory=None):
        return "Pikachu @ Light Ball"


class _DummyPlayer:
    """Stand-in for a RLTrajectoryPlayer slot. Tests mutate
    `inference_client` via `apply_opp_type_to_pair` and assert the
    expected client routed to this slot."""

    def __init__(self):
        self.opponent_type = "self_play"
        self.inference_client: object = None


def _clients_with(*names: str) -> MagicMock:
    """Build a fake `worker_inference_clients` bundle exposing exactly
    these model names. Mirrors WorkerInferenceClients' dict-style API
    (`clients[name]` strict, `clients.get(name)` returns None on miss,
    `name in clients` for membership).
    """
    per_name = {name: MagicMock(name=f"{name}_client") for name in names}
    clients = MagicMock()
    clients.__getitem__ = MagicMock(side_effect=lambda n: per_name[n])
    clients.get = MagicMock(side_effect=lambda n: per_name.get(n))
    clients.__contains__ = MagicMock(side_effect=lambda n: n in per_name)
    return clients


def _make_factory(
    curriculum,
    worker_inference_clients=None,
    battle_formats=None,
    agent_team_paths=None,
):
    """Construct a factory with sensible defaults. Tests that only
    exercise pure-state methods (e.g. `set_active_*_slots`) can rely on
    the default stub bundle; tests that actually route inference should
    pass a pre-built bundle from `_clients_with(...)`.
    """
    if battle_formats is None:
        battle_formats = {"gen9vgc2023regc": 1.0}
    return WorkerOpponentFactory(
        team_repo=cast(TeamRepo, _DummyTeamRepo()),
        battle_formats=battle_formats,
        opponent_team_subdirectories={fmt: None for fmt in battle_formats},
        server_config=cast(ServerConfiguration, SimpleNamespace()),
        curriculum=curriculum,
        embedder=cast(Embedder, SimpleNamespace()),
        worker_id=0,
        run_id="0000",
        worker_inference_clients=worker_inference_clients or _clients_with(),
        agent_team_paths=agent_team_paths,
    )


def _sample_and_apply(factory, player, opponent):
    """Test helper: run the two-step dispatch (sample type, then apply
    swaps to the BIP pair) and return the final opp_type."""
    p = cast(RLTrajectoryPlayer, player)
    o = cast(RLTrajectoryPlayer, opponent)
    opp_type = factory.sample_opp_type_for(p)
    return factory.apply_opp_type_to_pair(p, o, opp_type)


def test_train_exploiter_swaps_both_clients_when_provisioned():
    """When TRAIN_EXPLOITER is sampled and both co-training InferenceClients
    are provisioned, player swaps to the exploiter client and opponent to
    the victim client. The trajectory tag (`opponent_type`) is what
    main-process routing uses to direct the trajectory to the exploiter
    learner."""
    clients = _clients_with("main", "exploiter", "victim")
    factory = _make_factory({"train_exploiter": 1.0}, worker_inference_clients=clients)

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.TRAIN_EXPLOITER
    assert player.opponent_type == OpponentPool.TRAIN_EXPLOITER
    assert player.inference_client is clients.get("exploiter")
    assert opponent.inference_client is clients.get("victim")


def test_player_resets_to_main_after_train_exploiter_batch():
    """Regression: after a successful TRAIN_EXPLOITER batch leaves
    player.inference_client pointed at the exploiter client, the *next*
    batch (whatever its opp type) must reset the player to "main" so
    that subsequent trajectories aren't generated by the exploiter
    policy while tagged as something else (e.g. self_play). Reset has
    to happen even for heuristic / VGCBench batches that skip
    apply_opp_type_to_pair entirely — which is why it lives in
    sample_opp_type_for.
    """
    clients = _clients_with("main", "exploiter", "victim")
    factory = _make_factory({"train_exploiter": 1.0}, worker_inference_clients=clients)

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    # Batch 1: train_exploiter → player ends up on "exploiter".
    _sample_and_apply(factory, player, opponent)
    assert player.inference_client is clients.get("exploiter")

    # Batch 2: curriculum flips to self_play. sample_opp_type_for alone
    # (no apply call for many opp types) must re-align player to main.
    factory.curriculum = {OpponentPool.SELF_PLAY: 1.0}
    opp_type = factory.sample_opp_type_for(cast(RLTrajectoryPlayer, player))
    assert opp_type == OpponentPool.SELF_PLAY
    assert player.inference_client is clients.get("main")

    # Batch 3: heuristic-style opp type — same expectation, even though
    # apply_opp_type_to_pair would not be called in prepare_batch_tasks.
    factory.curriculum = {OpponentPool.SELF_PLAY: 1.0}  # heuristic types
    # Simulate a stale exploiter assignment between batches.
    player.inference_client = clients.get("exploiter")
    factory.curriculum = {OpponentPool.MAX_DAMAGE: 1.0}
    opp_type = factory.sample_opp_type_for(cast(RLTrajectoryPlayer, player))
    assert opp_type == OpponentPool.MAX_DAMAGE
    assert player.inference_client is clients.get("main")


def test_train_exploiter_falls_back_when_unprovisioned():
    """If the curriculum activates train_exploiter before the main process
    has provisioned exploiter/victim InferenceClients, fall back to
    self-play and point opponent at the main client. The trajectory
    routes as main; main process is responsible for ensuring this race
    doesn't matter (warmup gate keeps weight at 0 until ready)."""
    clients = _clients_with("main")
    factory = _make_factory({"train_exploiter": 1.0}, worker_inference_clients=clients)

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.SELF_PLAY
    assert player.opponent_type == OpponentPool.SELF_PLAY
    assert opponent.inference_client is clients.get("main")


def _patch_rl_trajectory_player(monkeypatch):
    """Replace RLTrajectoryPlayer in opponents.py with a recording stub.

    Returns the list that captures kwargs of each construction so a test
    can assert what got passed.
    """
    captured_kwargs = []

    class _RecordingPlayer:
        def __init__(self, **kwargs):
            captured_kwargs.append(kwargs)

    monkeypatch.setattr("elitefurretai.rl.opponents.RLTrajectoryPlayer", _RecordingPlayer)
    return captured_kwargs


def test_create_player_pairs_omits_max_concurrent_when_none(monkeypatch):
    """Default config leaves max_concurrent_battles_per_player=None — the
    kwarg must not be passed to RLTrajectoryPlayer so poke-env's library
    default (1) stays in force. Forwarding a None would surface as an
    unexpected override.
    """
    clients = _clients_with("main")
    factory = _make_factory({"self_play": 1.0}, worker_inference_clients=clients)
    assert factory.max_concurrent_battles_per_player is None

    captured_kwargs = _patch_rl_trajectory_player(monkeypatch)
    factory.create_agents(num_pairs=2, local_traj_queue=cast(queue.Queue, None))

    assert len(captured_kwargs) == 4  # 2 pairs × (player + opponent)
    for kw in captured_kwargs:
        assert "max_concurrent_battles" not in kw


def test_create_player_pairs_passes_max_concurrent_when_set(monkeypatch):
    """When the config sets a concurrent-battle cap, every player and
    opponent constructed by create_player_pairs must receive it.
    """
    clients = _clients_with("main")
    factory = _make_factory({"self_play": 1.0}, worker_inference_clients=clients)
    factory.max_concurrent_battles_per_player = 16

    captured_kwargs = _patch_rl_trajectory_player(monkeypatch)
    factory.create_agents(num_pairs=3, local_traj_queue=cast(queue.Queue, None))

    assert len(captured_kwargs) == 6  # 3 pairs × (player + opponent)
    for kw in captured_kwargs:
        assert kw.get("max_concurrent_battles") == 16


def test_set_active_ghost_slots_updates_state():
    factory = _make_factory({"self_play": 1.0})
    assert factory._active_ghost_slots == set()
    factory.set_active_ghost_slots([0, 2, 4])
    assert factory._active_ghost_slots == {0, 2, 4}
    factory.set_active_ghost_slots([])
    assert factory._active_ghost_slots == set()


def test_ghosts_routes_via_active_slot():
    """When GHOSTS is sampled and slots are active, opponent gets a
    ghost_<slot> InferenceClient from the bundle."""
    clients = _clients_with("main", "ghost_0", "ghost_1", "ghost_2")
    factory = _make_factory({"ghosts": 1.0}, worker_inference_clients=clients)
    factory.set_active_ghost_slots([0, 1, 2])

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.GHOSTS
    assert player.opponent_type == OpponentPool.GHOSTS
    ghost_clients = {clients.get(f"ghost_{i}") for i in range(3)}
    assert opponent.inference_client in ghost_clients


def test_ghosts_falls_back_when_no_active_slots():
    """When GHOSTS is sampled but no slots are active, fall back to self-play
    in sample_opp_type_for (the defensive guard before any swap happens)."""
    clients = _clients_with("main")
    factory = _make_factory({"ghosts": 1.0}, worker_inference_clients=clients)
    # Note: deliberately NOT calling set_active_ghost_slots — empty by default.

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.SELF_PLAY


def test_set_active_exploiter_slots_updates_state():
    factory = _make_factory({"self_play": 1.0})
    assert factory._active_exploiter_slots == set()
    factory.set_active_exploiter_slots([0, 1, 2])
    assert factory._active_exploiter_slots == {0, 1, 2}
    factory.set_active_exploiter_slots([])
    assert factory._active_exploiter_slots == set()


def test_exploiters_routes_via_active_slot():
    """When EXPLOITERS is sampled and slots are active, opponent gets an
    exploiter_snap_<slot> InferenceClient from the bundle."""
    clients = _clients_with(
        "main", "exploiter_snap_0", "exploiter_snap_1", "exploiter_snap_2"
    )
    factory = _make_factory({"exploiters": 1.0}, worker_inference_clients=clients)
    factory.set_active_exploiter_slots([0, 1, 2])

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.EXPLOITERS
    assert player.opponent_type == OpponentPool.EXPLOITERS
    snap_clients = {clients.get(f"exploiter_snap_{i}") for i in range(3)}
    assert opponent.inference_client in snap_clients


def test_exploiters_falls_back_when_no_active_slots():
    """When EXPLOITERS is sampled but no slots are active, fall back to
    self-play in sample_opp_type_for (the defensive guard before any
    swap happens)."""
    clients = _clients_with("main")
    factory = _make_factory({"exploiters": 1.0}, worker_inference_clients=clients)
    # Note: deliberately NOT calling set_active_exploiter_slots — empty by default.

    player = _DummyPlayer()
    opponent = _DummyPlayer()

    selected = _sample_and_apply(factory, player, opponent)

    assert selected == OpponentPool.SELF_PLAY


def test_largest_remainder_apportionment_exact_split():
    """8 pairs across two formats 50/50 -> 4 of each."""
    result = largest_remainder_apportionment(num_items=8, weights={"a": 0.5, "b": 0.5})
    assert sorted(result) == ["a"] * 4 + ["b"] * 4


def test_largest_remainder_apportionment_handles_remainder():
    """5 pairs across 70/30 -> 4 of 'a', 1 of 'b'."""
    result = largest_remainder_apportionment(num_items=5, weights={"a": 0.7, "b": 0.3})
    counts = {fmt: result.count(fmt) for fmt in set(result)}
    assert counts == {"a": 4, "b": 1}


def test_largest_remainder_apportionment_deterministic():
    """Same inputs -> same output."""
    r1 = largest_remainder_apportionment(num_items=7, weights={"x": 0.4, "y": 0.6})
    r2 = largest_remainder_apportionment(num_items=7, weights={"x": 0.4, "y": 0.6})
    assert r1 == r2


def test_largest_remainder_apportionment_single_format():
    """Single-format distribution -> every slot gets that format."""
    result = largest_remainder_apportionment(num_items=4, weights={"only": 1.0})
    assert result == ["only"] * 4


def test_create_agents_assigns_pair_formats_via_apportionment(monkeypatch):
    """4 pairs at 50/50 should produce a pair_formats list with two of each format."""
    factory = _make_factory(
        curriculum={OpponentPool.SELF_PLAY: 1.0},
        worker_inference_clients=_clients_with("main"),
        battle_formats={"gen9vgc2024regg": 0.5, "gen9vgc2024regh": 0.5},
    )
    constructed_formats: list[str] = []

    class _StubPlayer:
        def __init__(self, *, battle_format, **kwargs):
            constructed_formats.append(battle_format)

    monkeypatch.setattr("elitefurretai.rl.opponents.RLTrajectoryPlayer", _StubPlayer)
    factory.create_agents(num_pairs=4, local_traj_queue=queue.Queue())
    assert sorted(factory.pair_formats) == [
        "gen9vgc2024regg",
        "gen9vgc2024regg",
        "gen9vgc2024regh",
        "gen9vgc2024regh",
    ]
    assert sorted(constructed_formats) == ["gen9vgc2024regg"] * 4 + ["gen9vgc2024regh"] * 4


def test_randomize_all_teams_uses_pair_format_per_slot(monkeypatch):
    """randomize_all_teams resamples each slot using self.pair_formats[i].

    Set up: factory with 4 pairs split 50/50 across two formats, with a
    curriculum that activates at least one baseline pool (max_damage)
    so the per-baseline-pool indexing is exercised too. Stub RLTrajectoryPlayer
    and MaxDamagePlayer so create_agents doesn't open websocket connections,
    then record every format passed to team_repo.sample_team during randomize.
    """
    sampled_formats: list[str] = []

    class _StubPlayer:
        def __init__(self, *, battle_format, **kwargs):
            self.battle_format = battle_format
            self._team = None

    monkeypatch.setattr("elitefurretai.rl.opponents.RLTrajectoryPlayer", _StubPlayer)
    monkeypatch.setattr("elitefurretai.rl.opponents.MaxDamagePlayer", _StubPlayer)

    class _RecordingTeamRepo:
        def sample_team(self, battle_format, subdirectory=None):
            sampled_formats.append(battle_format)
            return "Pikachu @ Light Ball"

        def _shuffle_team_order(self, team):
            return team

    factory = _make_factory(
        curriculum={OpponentPool.SELF_PLAY: 0.5, OpponentPool.MAX_DAMAGE: 0.5},
        battle_formats={"gen9vgc2024regg": 0.5, "gen9vgc2024regh": 0.5},
        worker_inference_clients=_clients_with("main"),
    )
    factory.team_repo = cast(TeamRepo, _RecordingTeamRepo())

    factory.create_agents(num_pairs=4, local_traj_queue=queue.Queue())

    # Sanity: 4 pairs apportioned 50/50 should give 2 of each format.
    assert sorted(factory.pair_formats) == [
        "gen9vgc2024regg",
        "gen9vgc2024regg",
        "gen9vgc2024regh",
        "gen9vgc2024regh",
    ]
    # Sanity: max_damage pool was built with one entry per pair (curriculum > 0).
    assert len(factory.max_damage_opponents) == 4

    # Now randomize. Expected calls per pool (each pool length = 4):
    #   - players (4)  -> get_agent_team -> sample_team(fmt) since no agent_team_paths
    #   - opponents (4) -> sample_team(fmt)
    #   - max_damage (4) -> sample_team(fmt)
    # = 12 calls total, with format matching factory.pair_formats[i] per slot.
    sampled_formats.clear()
    factory.randomize_all_teams()

    expected_per_pool = list(factory.pair_formats)
    expected = (
        expected_per_pool  # players
        + expected_per_pool  # opponents
        + expected_per_pool  # max_damage
    )
    assert sampled_formats == expected, (
        f"randomize_all_teams sampled wrong formats per slot.\n"
        f"  expected: {expected}\n"
        f"  actual:   {sampled_formats}"
    )
